//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lga
    {
        public int LgaID { get; set; }
        public int StateID { get; set; }
        public string LgaName { get; set; }
    
        public virtual State State { get; set; }
    }
}
