//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public long OrderID { get; set; }
        public long UserID { get; set; }
        public long ProductID { get; set; }
        public string ProductModelNumber { get; set; }
        public string UserName { get; set; }
        public decimal OrderUnitPrice { get; set; }
        public decimal OrderAmount { get; set; }
        public decimal GrandTotalAmount { get; set; }
        public int OrderQuantity { get; set; }
        public string OrderDeliveryOption { get; set; }
        public string OrderPaymentOption { get; set; }
        public string OrderTransactionNumber { get; set; }
        public string OrderTransactionStatus { get; set; }
        public string OrderDeliveryStatus { get; set; }
        public string OrderType { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Product Product { get; set; }
    }
}
