//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGatewayTransaction
    {
        public string TransactionID { get; set; }
        public string Email { get; set; }
        public string Date { get; set; }
        public string Total { get; set; }
        public string Method { get; set; }
        public string Status { get; set; }
        public string MerchantID { get; set; }
        public string MerchantRef { get; set; }
        public string Memo { get; set; }
        public string Referrer { get; set; }
        public Nullable<decimal> TotalCreditedToMerchant { get; set; }
        public string ExtraChargesByMerchant { get; set; }
        public Nullable<decimal> ProcessDuration { get; set; }
        public Nullable<decimal> TotalPaidByBuyer { get; set; }
        public string FundMaturity { get; set; }
        public string ChargesPaidByMerchant { get; set; }
    }
}
