//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Orders = new HashSet<Order>();
            this.ShoppingCarts = new HashSet<ShoppingCart>();
            this.WishLists = new HashSet<WishList>();
        }
    
        public long ProductID { get; set; }
        public int CategoryID { get; set; }
        public int SubCategoryID { get; set; }
        public string ProductSKU { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public decimal ProductUnitPrice { get; set; }
        public string ProductName { get; set; }
        public string ProductshortDesc { get; set; }
        public string ProductLongDesc { get; set; }
        public string ProductFrontView { get; set; }
        public string ProductSideView { get; set; }
        public string ProductFrontViewThumbnail { get; set; }
        public string ProductSideViewThumbnail { get; set; }
        public string ProductLocation { get; set; }
        public Nullable<decimal> ProductWeight { get; set; }
        public string ProductCreatedBy { get; set; }
        public Nullable<System.DateTime> ProductCreatedOn { get; set; }
        public Nullable<decimal> ProductDiscount { get; set; }
        public string ProductAvailability { get; set; }
        public string ProductColour { get; set; }
        public Nullable<bool> ProductIsNew { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
        public virtual ICollection<WishList> WishLists { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
