//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public long ShoppingCartRowID { get; set; }
        public long ProductID { get; set; }
        public string CartSessionID { get; set; }
        public string ProductSku { get; set; }
        public string FrontViewThumbNail { get; set; }
        public int ProductQuantity { get; set; }
        public string ProductName { get; set; }
        public decimal ProductTotalPrice { get; set; }
        public decimal ProductPrice { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserName { get; set; }
        public string DeliveryOption { get; set; }
        public string PaymentOption { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
