//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishList
    {
        public long WishListRowID { get; set; }
        public long ProductID { get; set; }
        public string WishListSessionID { get; set; }
        public string ProductName { get; set; }
        public decimal ProductTotalPrice { get; set; }
        public string ProductModelNumber { get; set; }
        public decimal ProductPrice { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public string UserName { get; set; }
        public string ProductSideViewThumb { get; set; }
        public string ProductFrontViewThumb { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
